import 'package:flutter/material.dart';
import 'package:flutterapp/your_20courseapp/generatedcursoswidget/generated/GeneratedJavaScriptWidget.dart';
import 'package:flutterapp/your_20courseapp/generatedcursoswidget/generated/GeneratedMySQLWidget.dart';
import 'package:flutterapp/your_20courseapp/generatedcursoswidget/generated/GeneratedHTML5Widget.dart';
import 'package:flutterapp/your_20courseapp/generatedcursoswidget/generated/Generated052Widget.dart';
import 'package:flutterapp/your_20courseapp/generatedcursoswidget/generated/GeneratedCSS3Widget.dart';
import 'package:flutterapp/your_20courseapp/generatedcursoswidget/generated/Generated041Widget.dart';
import 'package:flutterapp/your_20courseapp/generatedcursoswidget/generated/Generated021Widget.dart';
import 'package:flutterapp/your_20courseapp/generatedcursoswidget/generated/GeneratedLinuxWidget.dart';
import 'package:flutterapp/your_20courseapp/generatedcursoswidget/generated/GeneratedPHPWidget.dart';
import 'package:flutterapp/your_20courseapp/generatedcursoswidget/generated/GeneratedCursosWidget1.dart';
import 'package:flutterapp/your_20courseapp/generatedcursoswidget/generated/GeneratedVoltarWidget1.dart';
import 'package:flutterapp/your_20courseapp/generatedcursoswidget/generated/Generated011Widget.dart';
import 'package:flutterapp/your_20courseapp/generatedcursoswidget/generated/Generated061Widget.dart';
import 'package:flutterapp/your_20courseapp/generatedcursoswidget/generated/Generated031Widget.dart';

/* Frame cursos
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCursosWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 144.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 55.0,
                child: GeneratedCursosWidget1(),
              ),
              Positioned(
                left: 42.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: Generated052Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: Generated041Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 636.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: Generated011Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 309.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: Generated061Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: Generated031Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 745.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: Generated021Widget(),
              ),
              Positioned(
                left: 127.0,
                top: 214.0,
                right: null,
                bottom: null,
                width: 207.0,
                height: 55.0,
                child: GeneratedJavaScriptWidget(),
              ),
              Positioned(
                left: 127.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 55.0,
                child: GeneratedLinuxWidget(),
              ),
              Positioned(
                left: 127.0,
                top: 432.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 55.0,
                child: GeneratedMySQLWidget(),
              ),
              Positioned(
                left: 127.0,
                top: 541.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 55.0,
                child: GeneratedPHPWidget(),
              ),
              Positioned(
                left: 127.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 52.0,
                child: GeneratedHTML5Widget(),
              ),
              Positioned(
                left: 127.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 52.0,
                child: GeneratedCSS3Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 26.0,
                child: GeneratedVoltarWidget1(),
              )
            ]),
      ),
    ));
  }
}
