import 'package:flutter/material.dart';
import 'package:flutterapp/your_20courseapp/generatedprofessoreswidget/generated/GeneratedOlsouoCarlosWidget.dart';
import 'package:flutterapp/your_20courseapp/generatedprofessoreswidget/generated/GeneratedP21Widget.dart';
import 'package:flutterapp/your_20courseapp/generatedprofessoreswidget/generated/GeneratedOlsouaMaraWidget.dart';
import 'package:flutterapp/your_20courseapp/generatedprofessoreswidget/generated/GeneratedProfessoresWidget1.dart';
import 'package:flutterapp/your_20courseapp/generatedprofessoreswidget/generated/GeneratedVoltarWidget.dart';
import 'package:flutterapp/your_20courseapp/generatedprofessoreswidget/generated/GeneratedOlsouoCludioWidget.dart';
import 'package:flutterapp/your_20courseapp/generatedprofessoreswidget/generated/GeneratedP13Widget.dart';
import 'package:flutterapp/your_20courseapp/generatedprofessoreswidget/generated/GeneratedP11Widget.dart';
import 'package:flutterapp/your_20courseapp/generatedprofessoreswidget/generated/GeneratedOlsouaLuciaWidget.dart';
import 'package:flutterapp/your_20courseapp/generatedprofessoreswidget/generated/GeneratedP23Widget.dart';

/* Frame professores
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfessoresWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 83.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 55.0,
                child: GeneratedProfessoresWidget1(),
              ),
              Positioned(
                left: 27.0,
                top: 186.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 101.0,
                child: GeneratedP21Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 101.0,
                child: GeneratedP11Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 494.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 101.0,
                child: GeneratedP23Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 101.0,
                child: GeneratedP13Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 26.0,
                child: GeneratedVoltarWidget(),
              ),
              Positioned(
                left: 127.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 30.0,
                child: GeneratedOlsouaMaraWidget(),
              ),
              Positioned(
                left: 128.0,
                top: 376.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 30.0,
                child: GeneratedOlsouoCludioWidget(),
              ),
              Positioned(
                left: 128.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 30.0,
                child: GeneratedOlsouaLuciaWidget(),
              ),
              Positioned(
                left: 128.0,
                top: 685.0,
                right: null,
                bottom: null,
                width: 176.0,
                height: 30.0,
                child: GeneratedOlsouoCarlosWidget(),
              )
            ]),
      ),
    ));
  }
}
