import 'package:flutter/material.dart';
import 'package:flutterapp/your_20courseapp/generatedhomewidget/generated/Generated021Widget1.dart';
import 'package:flutterapp/your_20courseapp/generatedhomewidget/generated/GeneratedLogo22Widget.dart';
import 'package:flutterapp/your_20courseapp/generatedhomewidget/generated/GeneratedP12Widget.dart';
import 'package:flutterapp/your_20courseapp/generatedhomewidget/generated/GeneratedP13Widget1.dart';
import 'package:flutterapp/your_20courseapp/generatedhomewidget/generated/GeneratedCursosWidget2.dart';
import 'package:flutterapp/your_20courseapp/generatedhomewidget/generated/GeneratedProfessoresWidget2.dart';
import 'package:flutterapp/your_20courseapp/generatedhomewidget/generated/Generated061Widget1.dart';
import 'package:flutterapp/your_20courseapp/generatedhomewidget/generated/Generated052Widget1.dart';
import 'package:flutterapp/your_20courseapp/generatedhomewidget/generated/Generated031Widget1.dart';
import 'package:flutterapp/your_20courseapp/generatedhomewidget/generated/GeneratedP23Widget1.dart';
import 'package:flutterapp/your_20courseapp/generatedhomewidget/generated/GeneratedP21Widget1.dart';
import 'package:flutterapp/your_20courseapp/generatedhomewidget/generated/Generated041Widget1.dart';
import 'package:flutterapp/your_20courseapp/generatedhomewidget/generated/GeneratedP11Widget1.dart';
import 'package:flutterapp/your_20courseapp/generatedhomewidget/generated/GeneratedP22Widget.dart';
import 'package:flutterapp/your_20courseapp/generatedhomewidget/generated/Generated011Widget1.dart';

/* Frame home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 139.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 55.0,
                child: GeneratedCursosWidget2(),
              ),
              Positioned(
                left: 303.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: Generated021Widget1(),
              ),
              Positioned(
                left: 172.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: Generated052Widget1(),
              ),
              Positioned(
                left: 42.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: Generated041Widget1(),
              ),
              Positioned(
                left: 303.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: Generated011Widget1(),
              ),
              Positioned(
                left: 172.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: Generated061Widget1(),
              ),
              Positioned(
                left: 42.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: Generated031Widget1(),
              ),
              Positioned(
                left: 91.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 55.0,
                child: GeneratedProfessoresWidget2(),
              ),
              Positioned(
                left: 287.0,
                top: 682.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 101.0,
                child: GeneratedP12Widget(),
              ),
              Positioned(
                left: 159.0,
                top: 682.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 101.0,
                child: GeneratedP13Widget1(),
              ),
              Positioned(
                left: 31.0,
                top: 682.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 101.0,
                child: GeneratedP22Widget(),
              ),
              Positioned(
                left: 287.0,
                top: 573.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 101.0,
                child: GeneratedP23Widget1(),
              ),
              Positioned(
                left: 157.0,
                top: 573.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 101.0,
                child: GeneratedP11Widget1(),
              ),
              Positioned(
                left: 27.0,
                top: 573.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 101.0,
                child: GeneratedP21Widget1(),
              ),
              Positioned(
                left: 42.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 137.0,
                child: GeneratedLogo22Widget(),
              )
            ]),
      ),
    ));
  }
}
